import { authWebShellClasses } from '@funcup/shared';

/** Style ekranu profilu palarni (web). Łańcuchy Tailwind dosłowne — JIT. */
export const roasterProfileStyles = {
  pageWithPad: `${authWebShellClasses.page} pb-14`,
  narrowContent: 'mx-auto w-full max-w-[1200px] px-6 pt-6',
  narrowContentMain: 'mx-auto w-full max-w-[1200px] px-6 pt-6',
  mutedSmall: 'text-base text-vs-text-secondary',
  errorSmall: 'text-base text-vs-danger',
  successSmall: 'text-base text-vs-success',
  onboardingCard: 'mb-6 max-w-[760px] rounded-vs-md border-2 border-vs-border-strong bg-vs-elevated p-8 shadow-vs-sm',
  onboardingEyebrow: 'mb-3 text-sm font-semibold uppercase tracking-[0.18em] text-vs-text-secondary',
  onboardingTitle: 'font-display text-3xl uppercase tracking-[-0.03em] text-vs-text-primary',
  onboardingBody: 'mt-3 max-w-[580px] text-base leading-relaxed text-vs-text-secondary',
  onboardingNote: 'mt-4 rounded-vs-md border border-vs-border-default bg-vs-surface px-4 py-3 text-sm text-vs-text-secondary',
  viewCard: 'rounded-vs-md border-2 border-vs-border-strong bg-vs-elevated p-8 shadow-vs-sm',
  viewModeHint: 'mb-5 text-lg text-vs-text-secondary',
  dlRoot: 'grid gap-4 text-vs-text-primary md:grid-cols-2',
  dlTerm: 'text-xl font-normal normal-case tracking-normal text-vs-text-primary',
  definitionValue: 'mt-1 text-2xl font-medium uppercase leading-tight text-vs-text-primary',
  incompleteBanner: 'mt-5 rounded-vs-md border-2 border-vs-danger/30 bg-vs-danger/10 p-4 text-base text-vs-danger shadow-vs-sm',
  editCta: 'vs-button-primary mt-8 inline-flex items-center gap-2 text-lg font-semibold',
  formActionPrimary: 'vs-button-primary mt-8 inline-flex items-center gap-2 text-lg font-semibold',
  formActionSecondary: 'vs-button-secondary mt-3 inline-flex items-center gap-2 text-lg font-semibold',
  formCard: 'max-w-[760px] rounded-vs-md border-2 border-vs-border-strong bg-vs-elevated p-8 shadow-vs-sm',
  formCardLocked: 'opacity-60',
  formIntro: 'mb-5 text-lg text-vs-text-secondary',
  logoPreviewFrame: 'mt-2 flex h-28 w-28 items-center justify-center overflow-hidden rounded-vs-md border-2 border-vs-border-strong bg-vs-surface shadow-vs-sm',
  logoPreviewImage: 'h-full w-full object-contain',
  logoPlaceholder: 'text-sm text-vs-text-secondary',
  logoHelp: 'mt-2 text-sm text-vs-text-secondary',
  uploadFieldWrap: 'mt-2 rounded border border-vs-border-subtle/30 bg-vs-elevated p-2',
  submitError: 'mt-2 mb-4 text-base text-vs-danger',
  saveCta: 'vs-button-primary mt-3 mb-0 w-full max-w-[520px] py-3 text-2xl font-display uppercase tracking-[-0.02em]',
  cancelButton: 'vs-button-secondary mt-3 inline-flex items-center gap-2 text-lg font-semibold',
  fieldWrap: 'mb-4',
  fieldLabel: authWebShellClasses.fieldLabel,
  fieldInput: `${authWebShellClasses.input} mb-1 h-12 text-base`,
  fieldInputDisabled: 'cursor-not-allowed opacity-70',
  fieldError: '-mt-1 mb-1 text-sm text-vs-danger',
} as const;
