import { visualSystemTokens } from '@funcup/shared';
import { StyleSheet } from 'react-native';

const { colors, spacing, radius, typography } = visualSystemTokens;

/** Shared auth / form shell styles. */
export const authScreenStyles = StyleSheet.create({
  screen: {
    flex: 1,
    paddingHorizontal: spacing.md,
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  topSection: {
    width: '100%',
    maxWidth: 340,
    marginTop: spacing.xxl,
    alignItems: 'center',
  },
  separatorRow: {
    width: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: spacing.lg,
  },
  separatorLine: {
    flex: 1,
    height: 1,
    backgroundColor: colors.borderSubtle,
  },
  separatorText: {
    marginHorizontal: spacing.sm,
    fontSize: typography.bodyMD,
    color: colors.textSecondary,
    fontFamily: 'SplineSans_500Medium',
    lineHeight: typography.lineHeight.bodyMD,
  },
  socialButton: {
    width: '100%',
    height: 46,
    borderWidth: 1,
    borderColor: colors.borderStrong,
    borderRadius: radius.sm,
    backgroundColor: colors.surfaceElevated,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: spacing.md,
    gap: spacing.xs,
  },
  socialButtonText: {
    fontSize: typography.bodyMD,
    color: colors.textPrimary,
    fontFamily: 'SplineSans_500Medium',
    lineHeight: typography.lineHeight.bodyMD,
  },
  input: {
    width: '100%',
    height: 46,
    borderWidth: 1,
    borderColor: colors.borderDefault,
    borderRadius: radius.sm,
    backgroundColor: colors.surfaceElevated,
    paddingHorizontal: spacing.sm,
    color: colors.textPrimary,
    fontFamily: 'SplineSans_400Regular',
    marginBottom: spacing.sm,
  },
  fieldLabel: {
    width: '100%',
    fontSize: typography.bodySM,
    fontFamily: 'SplineSans_500Medium',
    color: colors.textPrimary,
    marginBottom: spacing.xs - 2,
    lineHeight: typography.lineHeight.bodySM,
  },
  fieldHint: {
    width: '100%',
    fontSize: typography.caption,
    fontFamily: 'SplineSans_400Regular',
    color: colors.textSecondary,
    marginTop: -(spacing.xs - 2),
    marginBottom: spacing.sm,
    lineHeight: typography.lineHeight.caption,
  },
  loginAction: {
    width: '100%',
    minHeight: 48,
    borderRadius: radius.md,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.accentPrimary,
    paddingHorizontal: spacing.md,
    marginTop: spacing.xs,
  },
  loginActionText: {
    fontSize: typography.bodyLG,
    fontFamily: 'SplineSans_700Bold',
    color: colors.textOnPrimary,
    lineHeight: typography.lineHeight.bodyLG,
  },
  registerPrompt: {
    marginBottom: spacing.lg,
    fontSize: typography.bodySM,
    fontFamily: 'SplineSans_400Regular',
    color: colors.textSecondary,
    lineHeight: typography.lineHeight.bodySM,
  },
  registerLink: {
    color: colors.accentPrimary,
    fontFamily: 'SplineSans_700Bold',
  },
  errorText: {
    width: '100%',
    fontFamily: 'SplineSans_400Regular',
    color: colors.danger,
    marginBottom: spacing.xs,
  },
  infoText: {
    width: '100%',
    fontFamily: 'SplineSans_400Regular',
    color: colors.success,
    marginBottom: spacing.xs,
  },
  centered: {
    width: '100%',
    justifyContent: 'center',
    alignItems: 'center',
  },
});
